### ISSUE TITLE
XQuery Troubleshoot

### ISSUE THREAD

**Issue by zme1** [zme1/toscana#21]
I just pushed a new XQuery file and HTML output on member sick compensation (the former is in my xquery folder, and the latter is in html/ssi/visualizations) and I'm trying to troubleshoot a problem I'm having with my output. The table is generating a row for each distinct recipient of sick compensation, but people who have received sums on multiple occasions still only have one single date and amount in their row. My XQuery code is pasted below:

```
let $targets := //tei:seg[@subtype='sick']/descendant::tei:persName[@role='target']/@ref
let $distinctTargets := distinct-values($targets)

for $distinctTarget in $distinctTargets
let $distinctTargetMatches := //tei:seg[@subtype='sick']/descendant::tei:persName[@role='target'][@ref = $distinctTarget]
for $distinctTargetMatch in $distinctTargetMatches
let $distinctTargetAmount := $distinctTargetMatch/(preceding-sibling::tei:num | following-sibling::tei:num)/@value/number()
let $distinctTargetMatchDate := $distinctTargetMatch/ancestor::tei:text/preceding-sibling::tei:teiHeader/descendant::tei:publicationStmt/tei:date/@when/string()
```

When I return `$distinctTargetMatchDate` and `$distinctTargetMatchAmount` only one value is generated for each, but about 15-20 members participated in at least 2 transactions. When I ignore the `for` loop I created for `$distinctTargetMatches` and just replace every instance of `$distinctTargetMatch` with `$distinctTargetMatches` in my code, all transactions are accounted for, but then a new `<tr>` is generated for every single transaction, with all the information repeated in each. I had this table working with more accuracy yesterday, and I don't know what I changed to muddy my output yesterday morning.

**Comment by djbpitt** [comment]
@zme1 What do you want the output to look like if a recipient participated in more than one transaction? In those situations, can we expect that the multiple transactions were always on different dates?

**Comment by zme1** [comment]
@djbpitt Yes, the only repeated compensations always fell on different dates. What I want to do is hold each member in one `<tr>`, and if they were given compensation on multiple occasions, liste each date and amount in their respective cells, separated by a newLine character.

**Comment by djbpitt** [comment]
@zme1 It sounds as if you want to merge the cells in the first column vertically if a person received multiple allocations. Markdown doesn't do row and column merging in tables, but in (bad) ASCII art:

```text
______________________
| Zac | Monday  | $5 |
|     | Tuesday | $10|
______________________
```
Is that right?

**Comment by zme1** [comment]
@djbpitt Yes, that is how I picture the output looking in my mind's eye.

**Comment by djbpitt** [comment]
I think you want the `group by` feature of XQuery. See <https://www.w3.org/TR/xquery-30/#id-group-by>.

**Comment by zme1** [comment]
@djbpitt So I should revert my XQuery to its state in which there was a `<tr>` generated for each transaction, then group the rows with the same `@ref` value vertically?

**Comment by djbpitt** [comment]
How about the following:
1. Group by person, so that the transactions that pertain to the same person are contiguous.
1. If the transaction (which will become a `<tr>`) is followed by other transactions involving the same person, count those and use the value to set a `@rowspan` attribute on the first (person) `<td>`.
1. If the transaction is preceded by other transactions involving the same person, don’t create a person cell for any but the first transaction involving each person.

**Comment by zme1** [comment]
@djbpitt Okay, I'll see if I can give that a whirl this evening after my classes let out.

**Comment by djbpitt** [comment]
Two of the sickness events have multiple persons, e.g.:
```xml
<seg type="comp" subtype="sick"><persName ref="#barantip" role="target">Del
fratello Pietro Baranti</persName>che certificano<lb/>amalato dal 1o Aprile
1919 fino al 14 Aprile 1919<lb/>Con Certificato Medico<persName ref="#ribettig"
>Del Dr. G.T. Ribetti</persName><lb/>Il Raporto degli Ufli. Sanitari
<persName ref="#merciadrie">Eugenio Merciadri</persName><lb/>e <persName
ref="#giomettic">Carlo Giometti</persName>e’ Giustificato a quello<lb/>
<persName ref="#ribettig">del Dr. Ribetti</persName>non vi fu nessuna
oposizione a<lb/>riguardo il<rs ref="#fredianim">Presidente</rs>lo messe
all’approvazione<lb/>per Lassegno di Sussidio di $1.00 al giorno
questo<lb/>Nostro Regolamento fu aprovato di pagarci<lb/>
<persName ref="#barantip">Al flo Pietro Baranti</persName>la Somma di <num
type="monetary" value="14">$14.00</num></seg><lb/>
```
How would you like to process and render these in the table output?

**Comment by zme1** [comment]
@djbpitt The only name of immediate interest in any compensation segment is the person who has a `@role` value of `'target'`. When I processed the XQuery, I just specified that the only name I cared about was the person who carried that attribute value.

**Comment by djbpitt** [comment]
@zme1 Take a look at the new `XQuery/sickComp.xquery` file in the new `sick` branch. The output is in `html/ssi/visualizations/sickComp_table.html`. It outputs just one `<tr>` per person, so there’s no need to fuss with `@rowspan` attributes, and it separates multiple dates and amounts with `<br/>` elements within a single cell.

**Comment by zme1** [comment]
@djbpitt I just merged and pulled, and I'm giving it a look now...

**Comment by zme1** [comment]
@djbpitt Looking at your modified file, the code you wrote seems more reminiscent of XSLT writing that seems a bit more familiar to me. I'll look up what specific XQuery features you used and write comments into this file that you wrote, in the event that I decide to use XQuery again.

I'm honestly not even certain that XQuery was the best solution for this data. This particular situation seemed to have some of the same qualities that made my working with accettati and cancellati in XSLT much more slippery, so I figured I would try with XQuery. Thank you for the pull request and for your advice earlier, and I'm sorry I wasn't fully able to put the latter into practice.

**Comment by zme1** [comment]
@djbpitt Meanwhile, I made a supplementary visualization for the table, and it's in the repo at html/ssi/visualizations/sickComp_line.html. If either you or @ebeshero want to give it a quick look and let me know if it's a viable graph to include in my work. 

It's still in rather crude form, but it's essentially a juxtaposition of how much money is given to members over the span of a year across each of the 7 years. The points on each line represent a month in a year (January being the first, and December being the last), and each individual line represents an entire year, start to finish. The numbers accumulate, so that at the end of the year the user can see how much money in total was given to members throughout the Lega. None of the axis markers are in yet, and all the lines are still just one color, which I plan to change with CSS/Javascript.

Neither this visualization nor the graph that David helped substantially with earlier clearly represent specific moments during a year in which a particular amount of money was awarded to members, but I don't think that it's much of a loss, considering that it wouldn't be able to tell the user much more than the line graph probably could right now. While it's not overtly specific on amounts given at one point, the user can see that to an extent on this visualization.

**Comment by zme1** [comment]
(It's in the ssi folder, despite it still being a full html file. I'm making that change now.)

**Comment by ebeshero** [comment]
Greetings from from Cincinnati, @zme1 ! I'm taking a look at your graphs now and I have some questions. 

1) You were specifically asking about [sickComp_line.html](http://htmlpreview.github.io/?https://github.com/zme1/toscana/blob/master/html/ssi/visualizations/sickComp_line.html) . Looking at this, I can see some interesting trends (higher comp demands in December every year, and lots of comp claims in 1921 and 1925. But it's a *little* difficult to read the line labels when you have a couple of year labels superimposed. I wonder if some color variation might help: a distinct color for each year? You may want to build this up to play with a little JavaScript so we can show all the lines and circles for a given year: you might want a legend that's really a form field in which visitors see the years in chronological order and click to show the ones they wish to see plotted.

 I see your SVG code has these marked off with `@class` attributes  (class="line1919", class="line1920", etc.) which should make them readily tractable to JavaScript. 

2) Looking at your graphs, I think we've spoken about [the one of Incoming and Outgoing Members](http://htmlpreview.github.io/?https://github.com/zme1/toscana/blob/master/html/ssi/visualizations/cancellatiAccettati_verticalBar.html) already. I like this plot as a legible summary, but the way you've output the raw data beneath it gave me and Stacey a moment of confusion just now because you've listed Incoming on the left (underneath your outgoing plot). Reversing that should help, unless you had a reason to list it that way. So, what happens with all the new members entering in 1925? My sense is that this graph is visually introducing the Lega in a set of transformative years--is this part of a story you want to tell with this project? When you stop showing data, do you have a sense of what happens next with the Lega? 

(By the way, here's how you can link to previews of your HTML and SVG files: you just need to tack this prefix: **http://htmlpreview.github.io/?** to the front of the file URL in the web toscana repo:
`http://htmlpreview.github.io/?https://github.com/zme1/toscana/blob/master/html/ssi/visualizations/sickComp_line.html`

@djbpitt Thanks for helping out with the XQuery today--I wish I were in the thick of this with you, but I've got a couple of conference roundtable panels to prepare tomorrow morning and Saturday afternoon! I'll keep looking in on this as I can. Anyway, @zme1 , one of the pleasures of reading @djbpitt 's XQuery is exactly when he writes things differently than you'd expect.

**Comment by zme1** [comment]
@ebeshero I'm planning on polishing the line graph tomorrow, adding different colors to the years and also some JavaScript to add dynamics to this specific graph, which will hopefully clarify the sets of data in it with more contrast in years. There are specific excerpts from the actual minutes that I think are worth comparing with the minutes as well, which could help contextualize the actual information of the graph. For much of 1924, the minutes show that a lot of energy was dedicated to expanding membership and "group morale" as they put it. They re-elected a former present and incredibly active Lega member in 1925, and group memberships and member compensation skyrocketed, and I would imagine that overall group activity increased as well (hopefully I'll see a trend once I start my other visualization). Long story short, there could be some cool patterns in the data that align with the narrative in the minutes...
