### ISSUE TITLE
heatmap colors

### ISSUE THREAD

**Issue by djbpitt** [zme1/toscana#27]
@zme1 In the current XSLT that generates the heatmap (in the `heatmap` branch), we currently perform an XPath calculation to determine the colors (hue and lightness are constant, saturation increases with the number of committees). That method distributes the saturation values evenly over the range of numbers of committee memberships, but although it’s arithmetically balanced, arithmetic balance doesn’t necessarily translate to visual appeal. Instead of performing this calculation, it might be better to plan a palette in http://colorbrewer2.org and use those colors.

**Comment by ebeshero** [comment]
@zme1 We're just looking at your new version of [the heatmap](https://github.com/zme1/toscana/blob/master/xml/heatmap.svg)--and it looks terrific with those grid lines and boundaries denoting officers! It's neat to be able to see a few people start out as active members and become officers a while...and it's also neat to see continued activity after an officer stint! 

@djbpitt and I were just discussing this: perhaps you can add a tooltip to SVG so that on mouseover you get the person's name? More complex--try making a table of data visible on mouseover. That'll take a little JavaScript and you'll need to integrate this on an HTML page (but we have some code samples and I have a homework excercise on this)!
