### ISSUE TITLE
font-family and font-weight

### ISSUE THREAD

**Issue by djbpitt** [zme1/toscana#41]
@zme1 Times extra bold (font-weight of 900) looks heavy on the minutes pages. I’m ambivalent about the decorative header font; it’s a good match for the calligraphy of the headers, but also hard to read. Additionally, when you use it in line on <http://toscana.newtfire.org/html/aboutTeam.html> for the participant names, it makes the line spacing on that page erratic.

**Comment by ebeshero** [comment]
@djbpitt opened his issue 35 seconds before I did (humph!) Anyway, @zme1 I noticed you reduced the size of the header font you're using--and it looks good now--a nearly even match for the size of the swirly writing in the minutes headings. But I'm not sure I agree now with the heavy font-weight (set at 900) throughout the site which seems a little heavy and not well matched to the heading. I think you could probably reduce that (experiment a little). 

Now that your site is looking seriously professional, it's probably time to play with some CSS tricks for fonts that you may not have experimented with much before! Here's perhaps a good place to get started: https://3.7designs.co/blog/2008/06/10-examples-of-beautiful-css-typography-and-how-they-did-it/

**Comment by djbpitt** [comment]
Rex Parker, writing today:

> The answer that took me the longest to get was HUMPH (ironic, as I am H(arr)UMPHing at this puzzle right now). There is no way that HUMPH achieves "Well, I never!" levels of pique. HUMPH is way, way less offended. The definition (above) even says, "slightly"—"slightly scornful doubt or dissatisfaction." Truly bad clue.

With respect to typography more generally, Gabi pointed me toward https://practicaltypography.com/. My aesthetics and his aren’t always in full agreement, but it’s worth reading.

**Comment by ebeshero** [comment]
@djbpitt As a frequent user of the word "humph," I totally disagree with Rex on this one. As for butterick's, I am frequently landing on this page for single and double quotes: https://practicaltypography.com/straight-and-curly-quotes.html but hadn't spent much time there otherwise. 

@zme1 One thing to notice is how the swirly font interacts with Times New Roman on your aboutTeam.html page. Notice how the names are running into the bios next to them? That's a font and a  spacing issue, and you can control either one in a number of ways--it's worth taking some time to groom that a little.  
There's a school of thought that web reading is better facilitated by *sans serif* fonts rather than *serif* fonts (which are seen to be better for printed documents). I'm not sure I always agree, but you may want to consider what fonts pair more naturally with your swirly header font. Perhaps one of the sans serifs might be good...
